-- sourcePaymentKbn 支払い方識別
INSERT INTO m_name ("id","name_ident_cd","name_cd","name_ident_name","name_ident_note","name_display_seq","name_ss_ja","name_ss_en","name_ss_vi","name_rk","drawable_icon_url","ins_dttm","upd_dttm") VALUES (1,'sourcePaymentKbn','1','支払い方','',1,'現金','Cash','Tiền mặt','Cash','ic_source_cash','2025-02-01','2025-02-01');
INSERT INTO m_name ("id","name_ident_cd","name_cd","name_ident_name","name_ident_note","name_display_seq","name_ss_ja","name_ss_en","name_ss_vi","name_rk","drawable_icon_url","ins_dttm","upd_dttm") VALUES (2,'sourcePaymentKbn','2','支払い方','',2,'振込','Bank transfer','Chuyển khoản','transfer','ic_source_card','2025-02-01','2025-02-01');
INSERT INTO m_name ("id","name_ident_cd","name_cd","name_ident_name","name_ident_note","name_display_seq","name_ss_ja","name_ss_en","name_ss_vi","name_rk","drawable_icon_url","ins_dttm","upd_dttm") VALUES (3,'sourcePaymentKbn','3','支払い方','',3,'スイカ','Suika card','Thẻ Suika','Suika','ic_source_suica','2025-02-01','2025-02-01');
INSERT INTO m_name ("id","name_ident_cd","name_cd","name_ident_name","name_ident_note","name_display_seq","name_ss_ja","name_ss_en","name_ss_vi","name_rk","drawable_icon_url","ins_dttm","upd_dttm") VALUES (4,'sourcePaymentKbn','4','支払い方','',4,'その他','Other','Khác','Other',NULL,'2025-02-01','2025-02-01');
-- categoryKbn カテゴリー識別
INSERT INTO m_name ("id","name_ident_cd","name_cd","name_ident_name","name_ident_note","name_display_seq","name_ss_ja","name_ss_en","name_ss_vi","name_rk","drawable_icon_url","ins_dttm","upd_dttm") VALUES (5,'categoryKbn','1','カテゴリー','',1,'食べ物','Food','Ăn uống','Food','ic_category_food','2025-02-01','2025-02-01');
INSERT INTO m_name ("id","name_ident_cd","name_cd","name_ident_name","name_ident_note","name_display_seq","name_ss_ja","name_ss_en","name_ss_vi","name_rk","drawable_icon_url","ins_dttm","upd_dttm") VALUES (6,'categoryKbn','2','カテゴリー','',2,'輸送','Transportation','Di chuyển','Trans','ic_category_transport','2025-02-01','2025-02-01');
INSERT INTO m_name ("id","name_ident_cd","name_cd","name_ident_name","name_ident_note","name_display_seq","name_ss_ja","name_ss_en","name_ss_vi","name_rk","drawable_icon_url","ins_dttm","upd_dttm") VALUES (7,'categoryKbn','3','カテゴリー','',3,'美','Beauty','Làm đẹp','Beauty',NULL,'2025-02-01','2025-02-01');
INSERT INTO m_name ("id","name_ident_cd","name_cd","name_ident_name","name_ident_note","name_display_seq","name_ss_ja","name_ss_en","name_ss_vi","name_rk","drawable_icon_url","ins_dttm","upd_dttm") VALUES (8,'categoryKbn','4','カテゴリー','',4,'勉強','Study','Học tập','Study',NULL,'2025-02-01','2025-02-01');
INSERT INTO m_name ("id","name_ident_cd","name_cd","name_ident_name","name_ident_note","name_display_seq","name_ss_ja","name_ss_en","name_ss_vi","name_rk","drawable_icon_url","ins_dttm","upd_dttm") VALUES (9,'categoryKbn','5','カテゴリー','',5,'買い物','Shopping','Mua sắm','Shopping',NULL,'2025-02-01','2025-02-01');
INSERT INTO m_name ("id","name_ident_cd","name_cd","name_ident_name","name_ident_note","name_display_seq","name_ss_ja","name_ss_en","name_ss_vi","name_rk","drawable_icon_url","ins_dttm","upd_dttm") VALUES (10,'categoryKbn','6','カテゴリー','',6,'エンターテインメント','Entertainment','Giải trí','Entertainment',NULL,'2025-02-01','2025-02-01');